### ISSUE TITLE
Website for Documentation seems to be down

### ISSUE THREAD

**Issue by okaufmann** [Duffleman/pushman#13]
i can't reach http://pushman.dfl.mn/

**Comment by DuffleOne** [comment]
Yeah I can't continue to run the project with work, and since Laravel has made it so easy to do this in REDIS and NodeJS, I've found myself never needing this anymore.

You can find the full site with documentation at:
https://github.com/PushmanPHP/site/blob/master/resources/views/docs/index.blade.php

**Comment by okaufmann** [comment]
Yes I understand. Can you please add a notice to the README, so we know this Project is abadoned?
Thanks for your work ;).
