### ISSUE TITLE
Lumen

### ISSUE THREAD

**Issue by pjebs** [Duffleman/pushman#7]
Any chance this can be converted to a lumen app instead?
Will this work with hhvm?

**Comment by pjebs** [comment]
What's the difference between this repo and the other PHP library repo?

**Comment by vluzrmos** [comment]
I think that is the server, and the PHP Library is the class to send messages to that server.

Then... you need to send a new issue there.

**Comment by DuffleOne** [comment]
I don't plan on making this with Lumen but I guess the code is interchangeable if someone wants to branch and make it work. 

This package is the server itself that runs independantly of your project, and the [The PHP Library](https://github.com/PushmanPHP/pushman_php_library) is required via composer to interact with the server easily.

And yes, this runs with HHVM; the demo server currently has HHVM installed and currently ran into no issues.

**Comment by pjebs** [comment]
Do you install the zeroMQ binary the usual way for hhvm?

**Comment by DuffleOne** [comment]
For HHVM install the lib onto the OS as normal, but you'll need the HHVM version available here:

https://github.com/duxet/hhvm-zmq
- Edit: Seems to be odd, a few issues stating this repo doesn't work, I'm not 100% sure; I've removed HHVM on the demo server and it's running vanilla PHP instead to avoid issues :S

**Comment by pjebs** [comment]
Have you tried these?:

https://github.com/yybirdcf/zmq-extension-for-hhvm

https://github.com/no1youknowz/hhvm-zeromq-ext

**Comment by DuffleOne** [comment]
Neither yet, I'm not going to be on HHVM anymore; waiting it out for PHP7 to grab those tasty static-type features. Do let me know if you find success in one of these libraries; I really want to remove the ZeroMQ requirement but I can't quite see how yet.
I'll include your findings in the documentation with credit if you find success with HHVM

**Comment by pjebs** [comment]
What are the features you need from ZeroMQ. Perhaps I can program it in Golang and wrap it as a PHP extension.

This kind of thing is a lot lot easier to do with Golang.

**Comment by DuffleOne** [comment]
The loop the Pushman instance runs in, (see [Line 53 here](https://github.com/PushmanPHP/pushman/blob/master/app/Console/Commands/Pushman.php#L53), needs to have events injected into it. So the HTTP API uses ZeroMQ to push to that socket so the Pushman loop knows when to execute `handleEvent`

**Comment by pjebs** [comment]
Can you tell me line by line what each statement does. I definately think I can write something in golang OR at least write a daemon.

**Comment by pjebs** [comment]
Have you thought about this:
https://github.com/cmosguy/laravel-http-pushstream-broadcaster

**Comment by DuffleOne** [comment]
This package appears to replace the need for Pushman completely.

## 

Currently with ZeroMQ: 

The WAMPServer is constantly running in the background as a process, it is listening and managing connections; should it close down all clients disconnect; it still runs as a loop though so when a client pushes an event via the API, the code doesn't get executed within the loop.

The event package from the API needs to be injected into that loop, that is what ZeroMQ does.

So from Pushman.php under Console/Commands; we create a loop on 32 and a PushmanHandler on 33. From there were say, whenever ZeroMQ pushes you an event, execute 'handleEvent' WITHIN the loop so we have access to connected clients in context. (Line 35 to 38)

Then build a new public facing server on on the PUSHMAN_PORT, (8080), and start running that loop for incoming web socket connections.

## 

If you want to replace this process, and remove the need for ZeroMQ; you need to write a program that interacts with the WAMPServer so it can handle incoming connections in the context of the PushmanHandler class without breaking the loop so the API can inject events to broadcast.

Currently WAMPServer is built by the Ratchet guys, and ZeroMQ is built by React guys; I've had requests to replace both, since Ratchet's WAMP doesn't support HTTP 2.0 and React is a heavy extension to add to PHP;

**Comment by pjebs** [comment]
You should probably close this. I looked into creating HHVM PHP extensions and it looked a bit more complicated that I had time for. I think i'll just wait for PHP 7 too.
